version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: local-kumoh-mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: local-mysql
      MYSQL_CHARSET: utf8mb4
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: local-redis
    ports:
      - "6381:6379"