spring:
  config:
    import:
      - security/application-security.yml
      - security/application-mail.yml
      - security/application-s3.yml
      - security/application-db.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${prod-db.rdb.url}
    username: ${prod-db.rdb.username}
    password: ${prod-db.rdb.password}
  data:
    web:
      pageable:
        one-indexed-parameters:
          true

    redis:
      host: ${prod-db.redis.host}
      port: ${prod-db.redis.port}
      password: ${prod-db.redis.password}
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        hbm2ddl.auto: none
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: false
  flyway:
    enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
        exclude: "env, beans, mappings, configprops, scheduledtasks, threaddump, shutdown"
  server:
    port: ${actuator.port}
