name: CI - Gradle Build
# Event
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 권한 설정
permissions:
  contents: read

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-libs
          path: build/libs/*.jar